# Numpy

In [1]:
import numpy as np
print(np.__version__)

1.21.5


# Creating numpy array

In [2]:
#using list
l=[1,2,3,5]
arr=np.array(l)
print(arr)

[1 2 3 5]


In [3]:
#using tuple
a=1,2,34
arr=np.array(a)
print(a)

(1, 2, 34)


# Dimentional arrays

In [4]:
#0-D
arr=np.array(1)
print(arr)
print(arr.ndim)

1
0


In [5]:
#1-D
arr=np.array([1,2,3,4])
print(arr)
print(arr.ndim)

[1 2 3 4]
1


In [6]:
#2-D
arr=np.array([[1,2,3,4],[4,5,6,7]])
print(arr)
print(arr.ndim)

[[1 2 3 4]
 [4 5 6 7]]
2


In [7]:
#ndim
arr=np.array([1,2,3,4],ndmin=5)
print(arr)
print(arr.ndim)

[[[[[1 2 3 4]]]]]
5


# Accesing and Slicing  

In [8]:
#1-D
arr=np.array([1,2,3,4])
print(arr)
print(arr.ndim)
print(arr[a[0]])
print(arr[-1])
print(arr[0:3])


[1 2 3 4]
1
2
4
[1 2 3]


In [9]:
#2-D
arr=np.array([[1,2,3,4],[4,5,6,7]])
print(arr)
print(arr.ndim)
print(arr[1,1])
print(arr[0,2])
print(arr[0:1])
print(arr[:,0:1])

[[1 2 3 4]
 [4 5 6 7]]
2
5
3
[[1 2 3 4]]
[[1]
 [4]]


In [10]:
arr=np.array([[[1,2,3,4],[2,3,4,5]],
              [[4,5,6,7],[8,9,0,9]]])
print(arr)

[[[1 2 3 4]
  [2 3 4 5]]

 [[4 5 6 7]
  [8 9 0 9]]]


In [11]:
print(arr[0,1,1])
print(arr[1,0,3])
print(arr[0:1,0,2])
print(arr[0:-1,0:-1,3])

3
7
[3]
[[4]]


# functions

In [12]:
#shape
arr1=np.array([1,2,3,4])
arr2=np.array([[1,2,3],[5,6,7]])

In [13]:
print(np.shape(arr1))
print(np.shape(arr2))

(4,)
(2, 3)


In [14]:
#dtype
arr1.dtype

dtype('int32')

In [15]:
#itemsize
arr1.itemsize

4

In [16]:
#total size
arr1.size

4

In [17]:
#reshape
a=np.array([1,2,3,4,5,6,7,8])
print(np.reshape(a,(4,2)))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [18]:
a=np.array([1,2,3,4,5,6,7,8])
print(np.reshape(a,(1,8)))

[[1 2 3 4 5 6 7 8]]


# Changing Elements

In [19]:
a=np.array([[1,2,3],[5,6,7]])
print(a)
a[0:1]=[6,6,6]
print(a)

[[1 2 3]
 [5 6 7]]
[[6 6 6]
 [5 6 7]]


In [20]:
a=np.array([[[1,2,3],[5,6,7]],
            [[6,7,8],[5,5,7]]])
print(a)
a[0:1,0,]=[1,1,1]
print(a)

[[[1 2 3]
  [5 6 7]]

 [[6 7 8]
  [5 5 7]]]
[[[1 1 1]
  [5 6 7]]

 [[6 7 8]
  [5 5 7]]]


# initializing different types of elements


In [21]:
#zeros
print( np.zeros((),dtype='int32'))
print( np.zeros((5),dtype='int32'))
print( np.zeros((2,2),dtype='int32'))
print( np.zeros((1,2,3),dtype='int32'))


0
[0 0 0 0 0]
[[0 0]
 [0 0]]
[[[0 0 0]
  [0 0 0]]]


In [22]:
import numpy as np
print( np.zeros((2,2,3),dtype='int32'))
print("\n")
print( np.zeros((2,3,3),dtype='int32'))

print( np.zeros((4,3,3),dtype='int32'))

[[[0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]]]


[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]


In [23]:
#ones
print( np.ones((),dtype='int32'))
print( np.ones((5),dtype='int32'))
print( np.ones((2,2),dtype='int32'))
print( np.ones((1,2,3),dtype='int32'))

1
[1 1 1 1 1]
[[1 1]
 [1 1]]
[[[1 1 1]
  [1 1 1]]]


In [24]:
#our own elements
print( np.full((),2,dtype='int32'))
print( np.full((5),4,dtype='int32'))
print( np.full((2,2),5,dtype='int32'))
print( np.full((1,2,3),6,dtype='int32'))

2
[4 4 4 4 4]
[[5 5]
 [5 5]]
[[[6 6 6]
  [6 6 6]]]


In [25]:
#accesing 1-D array elements
a1=np.array([1,2,3])
print(a1)
for i in a1:
    print(i)

[1 2 3]
1
2
3


In [26]:
#accesing 2-D array elements 
a2=[[1,2,3],[6,7,8]]
print(a2)
for i in a2:
    print(i)

[[1, 2, 3], [6, 7, 8]]
[1, 2, 3]
[6, 7, 8]


In [27]:
for i in a2:
    for j in i:
        print(j)

1
2
3
6
7
8


# operations on numpy 

In [28]:
#arithmatic operations
a=np.array([1,2,3])
b=np.array([8,5,3])
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[9 7 6]
[-7 -3  0]
[ 8 10  9]
[0.125 0.4   1.   ]


In [29]:
#logical operations and coparision
print(np.logical_and(a,b))
print(np.logical_or(a,b))
print(np.logical_not(a))
print(np.logical_and(a,b))
print(np.logical_xor(a,b))
print(np.less(a,b))
print(np.equal(a,b))
print(np.greater(a,b))
print(np.greater_equal(a,b))



[ True  True  True]
[ True  True  True]
[False False False]
[ True  True  True]
[False False False]
[ True  True False]
[False False  True]
[False False False]
[False False  True]


In [30]:
#trignometric operations
print(np.cos(a))
print(np.sin(a))
print(np.tan(a))


[ 0.54030231 -0.41614684 -0.9899925 ]
[0.84147098 0.90929743 0.14112001]
[ 1.55740772 -2.18503986 -0.14254654]


In [31]:
#constants
print(np.pi) 
print(np.e)
print(np.exp(10))

3.141592653589793
2.718281828459045
22026.465794806718


# Mathematics

In [32]:
a1+a2

array([[ 2,  4,  6],
       [ 7,  9, 11]])

In [33]:
a1-a2

array([[ 0,  0,  0],
       [-5, -5, -5]])

In [34]:
a1/a2

array([[1.        , 1.        , 1.        ],
       [0.16666667, 0.28571429, 0.375     ]])

In [35]:
a1**2

array([1, 4, 9], dtype=int32)

# Statistics

In [36]:
print(np.min(a1))
print(np.max(a1))
print(np.mean(a1))
print(np.std(a1))
print(np.median(a1))


1
3
2.0
0.816496580927726
2.0


# linear algebra

In [37]:
''' rank , transpose,inverse , det,
product -> inner , outer , dot
solve equations
eigen values and eigen vectors'''


' rank , transpose,inverse , det,\nproduct -> inner , outer , dot\nsolve equations\neigen values and eigen vectors'

In [38]:
#rank
a=np.random.randint(1,9,(3,3))
print(a)
print(np.linalg.matrix_rank(a))
print(np.transpose(a))
print(np.linalg.inv(a))
print(np.linalg.det(a))


[[2 6 8]
 [4 5 5]
 [1 1 8]]
3
[[2 4 1]
 [6 5 1]
 [8 5 8]]
[[-0.35  0.4   0.1 ]
 [ 0.27 -0.08 -0.22]
 [ 0.01 -0.04  0.14]]
-100.00000000000004


In [39]:
#eigen values and eigen vectors
print(a)
val,vect=np.linalg.eig(a)
print(val,vect)

[[2 6 8]
 [4 5 5]
 [1 1 8]]
[11.83603817 -1.72731457  4.89127641] [[ 0.67735496  0.87144003 -0.48564166]
 [ 0.64929632 -0.4889232  -0.77449334]
 [ 0.34583891 -0.03932399  0.40535447]]


In [40]:
#solving the linear equation
a=[[2,3,4],
  [4,5,8],
   [3,4,5]]
b=[1,5,7]
print(np.linalg.solve(a,b))

[13. -3. -4.]


In [41]:
#product
#dot
a=np.random.randint(1,20,(3,3))
b=np.random.randint(1,30,(3,3))
print(a)
print(b)
print(np.dot(a,b))



[[ 1  1 16]
 [ 8  4 11]
 [ 2 13 10]]
[[ 1  8  5]
 [25 21 21]
 [15 16 15]]
[[266 285 266]
 [273 324 289]
 [477 449 433]]


In [42]:
#inner
print(np.inner(a,b)) 

[[ 89 382 271]
 [ 95 515 349]
 [156 533 388]]


In [43]:
#outer
print(np.outer(a,b))

[[  1   8   5  25  21  21  15  16  15]
 [  1   8   5  25  21  21  15  16  15]
 [ 16 128  80 400 336 336 240 256 240]
 [  8  64  40 200 168 168 120 128 120]
 [  4  32  20 100  84  84  60  64  60]
 [ 11  88  55 275 231 231 165 176 165]
 [  2  16  10  50  42  42  30  32  30]
 [ 13 104  65 325 273 273 195 208 195]
 [ 10  80  50 250 210 210 150 160 150]]


# random module

In [44]:
#decimal 0-1
from numpy import random
print(np.random.rand(1))
print(np.random.rand(2,2))
print(np.random.rand(1,2,4))

[0.68268369]
[[0.93780191 0.47123906]
 [0.00143938 0.32686943]]
[[[0.80893154 0.04140642 0.34017446 0.08854778]
  [0.92970763 0.81380326 0.88117831 0.03387538]]]


In [45]:
#integer
print(np.random.randint(1))
print(np.random.randint(2,10,(2,2)))
print(np.random.randint(1,100,(3,3)))

0
[[7 6]
 [6 6]]
[[65 38 24]
 [79 59 41]
 [65 13 89]]


In [46]:
#choose -> create a array from existing one
a=np.array([1,2,3,4])
print(np.random.choice(a))


3


# be careful while dealing with copy

In [47]:
#copy doesnt change the original array
a=np.array([1,2,3])     
print(a)
b=np.copy(a)
b[0]=10
print(b)
print(a)


[1 2 3]
[10  2  3]
[1 2 3]


In [48]:
#view does change the original array
a=np.array([1,2,3])     
print(a)
b=a.view()
b[0]=10
print(b)
print(a)

[1 2 3]
[10  2  3]
[10  2  3]


# searching and sorting

In [49]:
#searching
a=np.array([1,2,7,4,29,8])
print(a)
b=np.searchsorted(a,2)
print(b)

[ 1  2  7  4 29  8]
1


In [50]:
#sorting
a=np.array([1,2,7,4,29,8])
print(a)
b=np.sort(a)
print(b)

[ 1  2  7  4 29  8]
[ 1  2  4  7  8 29]


In [51]:
#count
a=np.array([1,2,7,4,29,8])
print(a)
b=np.count_nonzero(a)
print(b)

[ 1  2  7  4 29  8]
6


# stacking


In [52]:
#hstack
a=np.random.randint(1,5,(1,5))
b=np.random.randint(1,10,(1,5))
print(a)
print(b)
print(np.hstack([a,b]))

[[3 2 2 3 3]]
[[6 3 1 3 9]]
[[3 2 2 3 3 6 3 1 3 9]]


In [53]:
#hstack
a=np.random.randint(1,5,(1,5))
b=np.random.randint(1,10,(1,5))
print(a)
print(b)
print(np.vstack([a,b]))

[[4 1 4 4 3]]
[[4 9 9 7 3]]
[[4 1 4 4 3]
 [4 9 9 7 3]]


# interpolate

In [54]:
days=np.array([1,3,5,7])
price=np.array([20,30,23,45])
remain=np.interp(32,days,price)
print(remain)

45.0


In [55]:
days=np.array([1,3,5,7])
price=np.array([20,30,23,45])
find=[2,6]
remain=np.interp(find,days,price)
print(remain)

[25. 34.]


In [56]:
import numpy as np
days=np.array(['sun','mon','tues','wed'])
sal=np.array([10,20,30,40])
interday=np.array(['fri','sat'])
day_map = {'sun': 0, 'mon': 1, 'tues': 2, 'wed': 3, 'thurs': 4, 'fri': 5, 'sat': 6}
#convering days to int
day_int=np.array([day_map[day]  for day in days])
interday_int=np.array([day_map[day]  for day in interday])
print(np.interp(interday_int,day_int,sal))

[40. 40.]


# boolean indexing and fancy indexing

In [57]:
#boolean indexing
old=np.array([1,2,3,4])
print(old)
boolean_mask=old>3
result=old[boolean_mask]

print(result)

[1 2 3 4]
[4]


In [58]:
#fancy indexing
old=np.array([1,2,3,4])
select_elements=old[[1,2]]
print(select_elements)


[2 3]


In [59]:
#boolean indexing
old=np.array([1,2,3,4])
print(old)
boolean_mask=old>3
result=old[old>3]

print(result)

[1 2 3 4]
[4]
